Call api method before the external library is loaded
CrossLead/angular-zendesk-widget pull request #8
Opened 2016-09-15 14:11 UTC by mrbatista

Before call api method is necessary to ensure that external library is loaded.
```javascript
angular.forEach(apiMethods, function(method) {
 ZendeskWidgetApi.prototype[method] = function() {
  $window.zE[method].apply($window.zE, arguments);
 };
});
```
It's possible that `$windows.zE[method]` is `undefined` if library is not loaded.
This PR fix this issue

2016-09-15 14:12 UTC, mrbatista commented
@bsouthga PTAL

2016-09-15 14:18 UTC, yangchristian requested changes
Unfortunately [Travis is failing](https://travis-ci.org/CrossLead/angular-zendesk-widget/builds/160177575). Looks like there are loading problems with this approach to bootstrapping.

2016-09-15 14:27 UTC, mrbatista commented
@yangchristian all api support "before page load". see [official documentation](https://developer.zendesk.com/embeddables/docs/widget/api)

2016-09-15 16:51 UTC, yangchristian commented
Hmm, looks like then we'll need to adjust the tests so that continuous integration doesn't fail. In particular, we'll need to modify the [`mock service`](https://github.com/CrossLead/angular-zendesk-widget/blob/f6d271e030a622777b32420fdb720589c49c819b/test/unit/services/zendeskWidgetProviderSpec.js#L15). Let me know if you have time to take a look, otherwise I can probably get to it this weekend. Thanks!

2016-09-18 21:11 UTC, yangchristian commented on src/angular-zendesk-widget/zendeskWidget.service.js
> +                $window.zE[method].apply($window.zE, arguments);
This is a bug: `arguments` now blanks out due to the closure. Think you need to do something like this:

```js
            ZendeskWidgetApi.prototype[method] = function() {
            var closureArgs = arguments;
              $window.zE(function() {
                $window.zE[method].apply($window.zE, closureArgs);
              })
            };
```

2016-09-18 21:11 UTC, yangchristian commented
@mrbatista: Couple updates:

- I updated the tests. Can you merge latest `master` into your branch?
- There is a bug with the change: please see the line note

Thanks!

2016-09-19 08:29 UTC, mrbatista commented on src/angular-zendesk-widget/zendeskWidget.service.js
> +                $window.zE[method].apply($window.zE, arguments);
Fixed!

2016-09-19 08:40 UTC, mrbatista commented
@yangchristian PTAL

2016-09-19 17:25 UTC, yangchristian approved these changes

2016-09-19 17:25 UTC, merged

2016-09-19 17:26 UTC, yangchristian commented
@mrbatista: merged. Thanks for the contrib!

2016-09-22 13:10 UTC, mrbatista commented
@yangchristian please publish new version on bower. Thanks!

2016-09-23 02:04 UTC, yangchristian commented
@mrbatista: v0.1.1 up. Thanks again!